export default {
  pre: {
    mdomain: 'http://m-awall.stage.ds.gome.com.cn',
    adRequestApi: 'http://ad-flitght.pre.ds.gome.com.cn/flight',
    pariseShareBatch: 'http://ad-shareserver.pre.ds.gome.com.cn/pariseShareBatch',
    parise: 'http://ad-shareserver.pre.ds.gome.com.cn/parise',
    discoveryShare: 'http://ad-shareserver.pre.ds.gome.com.cn/discoveryShare',
    shareRebateUrl: 'http://ad-shareserver.pre.ds.gome.com.cn/shareRebate',
    rebateBudgetUrl: 'http://ad-shareserver.pre.ds.gome.com.cn/rebateBudget',
    shareSuccessCount: 'http://ad-shareserver.pre.ds.gome.com.cn/shareSuccCount',
    videoSetCount: 'http://count-v.pre.video.api/set/video/',
    videoGetCount: 'http://count-v.pre.video.api/get/video/',
    middlePageUrl: 'http://m-awall.stage.ds.gome.com.cn',
    getVideoUrl: 'http://gvsout.pre.video.api',
    getPariseInfo: 'http://ad-shareserver.pre.ds.gome.com.cn/pariseInfo',
    videoShareUrl: 'http://ad-shareserver.pre.ds.gome.com.cn/video',
    questionRebateUrl: 'http://ad-shareserver.pre.ds.gome.com.cn/questionRebate',
    questionViewUrl: 'http://ad-shareserver.pre.ds.gome.com.cn/questionView',
    middlePageImpressionUrl: 'http://ad-shareserver.pre.ds.gome.com.cn/mp',
    questionInvestAppearUrl: 'http://ad-shareserver.pre.ds.gome.com.cn/questionInvestAppear',
    impression: 'http://ad-impression.pre.ds.gome.com.cn',
    slots: {
      topicSlotId: 10836,
      shopSlotId: 10837,
      itemSlotId: 10838,
      videoSlotId: 10840,
      productSlotId: 10839,
    }
  },
  pro: {
    mdomain: 'https://mm.gome.com.cn',
    adRequestApi: 'https://flight.gome.com.cn/flight',
    pariseShareBatch: 'https://shareserver.gome.com.cn/pariseShareBatch',
    parise: 'https://shareserver.gome.com.cn/parise',
    discoveryShare: 'https://shareserver.gome.com.cn/discoveryShare',
    shareRebateUrl: 'https://shareserver.gome.com.cn/shareRebate',
    rebateBudgetUrl: 'https://shareserver.gome.com.cn/rebateBudget',
    shareSuccessCount: 'https://shareserver.gome.com.cn/shareSuccCount',
    videoSetCount: 'https://count-v.gomeplus.com/set/video/',
    videoGetCount: 'https://count-v.gomeplus.com/get/video/',
    middlePageUrl: 'https://mm.gome.com.cn',
    getVideoUrl: 'https://api-v.gomeplus.com',
    getPariseInfo: 'https://shareserver.gome.com.cn/pariseInfo',
    videoShareUrl: 'https://shareserver.gome.com.cn/video',
    questionRebateUrl: 'https://shareserver.gome.com.cn/questionRebate',
    questionViewUrl: 'https://shareserver.gome.com.cn/questionView',
    middlePageImpressionUrl: 'https://shareserver.gome.com.cn/middlePageImpression',
    questionInvestAppearUrl: 'https://shareserver.gome.com.cn/questionInvestAppear',
    impression: 'https://impression.gome.com.cn',
    slots: {
      topicSlotId: 10132,
      shopSlotId: 10133,
      itemSlotId: 10134,
      videoSlotId: 10136,
      productSlotId: 10135,
    }
  },
  mapKey: 'e7a88a59789635c40499117b257bffa8',
  adType: {
    '44': 'product',
    '45': 'item',
    '46': 'topic',
    '47': 'video',
    '48': 'shop'
  }
};